CREATE TABLE IF NOT EXISTS hp_wechat_refunds (
	refund_record_id VARCHAR(64) NOT NULL,
	merchant_refund_no VARCHAR(64) NOT NULL,
	idempotency_key VARCHAR(128) NOT NULL,
	source VARCHAR(32) NOT NULL,
	source_order_id VARCHAR(64) NOT NULL,
	out_trade_no VARCHAR(32) NOT NULL,
	total_fen BIGINT UNSIGNED NOT NULL,
	refund_fen BIGINT UNSIGNED NOT NULL,
	reason VARCHAR(80) NULL,
	status VARCHAR(32) NOT NULL,
	provider_status VARCHAR(16) NULL,
	provider_refund_id VARCHAR(32) NULL,
	provider_transaction_id VARCHAR(32) NULL,
	provider_request_id VARCHAR(128) NULL,
	success_time VARCHAR(64) NULL,
	last_error_code VARCHAR(128) NULL,
	version INT UNSIGNED NOT NULL,
	created_at DATETIME(3) NOT NULL,
	updated_at DATETIME(3) NOT NULL,
	PRIMARY KEY (refund_record_id),
	UNIQUE KEY uq_hp_wechat_refunds_merchant_no (merchant_refund_no),
	UNIQUE KEY uq_hp_wechat_refunds_idempotency (idempotency_key),
	KEY idx_hp_wechat_refunds_source_order (source, source_order_id, status),
	KEY idx_hp_wechat_refunds_updated (updated_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
